export const mockDevices = [
  {
    id: "1",
    name: "Gas Sensor - Kitchen",
    type: "Gas Detector",
    location: "Kitchen, First Floor",
    status: "Online" as const,
    battery: 85,
    lastSeen: "3 minutes ago",
  },
  {
    id: "2",
    name: "Smoke Detector - Bedroom",
    type: "Smoke Detector",
    location: "Master Bedroom, Second Floor",
    status: "Online" as const,
    battery: 18,
    lastSeen: "6 minutes ago",
  },
  {
    id: "3",
    name: "Temp Sensor - Living Room",
    type: "Temperature Sensor",
    location: "Living Room, First Floor",
    status: "Online" as const,
    battery: 92,
    lastSeen: "2 minutes ago",
  },
  {
    id: "4",
    name: "Motion Sensor - Garage",
    type: "Motion Detector",
    location: "Garage, Ground Floor",
    status: "Online" as const,
    battery: 67,
    lastSeen: "11 minutes ago",
  },
  {
    id: "5",
    name: "Water Leak Detector",
    type: "Water Sensor",
    location: "Basement",
    status: "Offline" as const,
    battery: 0,
    lastSeen: "about 2 hours ago",
  },
  {
    id: "6",
    name: "Fire Alarm - Hallway",
    type: "Fire Detector",
    location: "Second Floor Hallway",
    status: "Online" as const,
    battery: 100,
    lastSeen: "4 minutes ago",
  },
];